# -*- mode: ruby -*-
# vi: set ft=ruby :

##Provisioner Section

#Update Host
$update = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
apt update -y
apt -qy -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" upgrade
SCRIPT
#End of script

#Install script for docker
$docker = <<SCRIPT
apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update -y
apt-get install -y docker-ce docker-ce-cli containerd.io
usermod -aG docker vagrant
newgrp docker
SCRIPT
#End of Script

#Install script for Docker Compose
$compose = <<SCRIPT
curl -L 'https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-x86_64' -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
SCRIPT
#End of Script
##End of Provisioning Section

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt"
  config.vm.box = "roboxes/ubuntu2210"
  config.vm.network "private_network", ip: "192.168.60.3"
  config.vm.provision "shell", inline: $update
  config.vm.provision "shell", inline: $docker
  config.vm.provision "shell", inline: $compose
end